/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, Font, Typograph } from "@diez/prefabs";

const legrandePortals20200301Colors = {
    darkBlue: Color.rgba(14, 36, 57, 1),
    grey1: Color.rgba(52, 52, 52, 1),
    grey2: Color.rgba(78, 80, 82, 1),
    grey3: Color.rgba(151, 153, 155, 1),
    grey5: Color.rgba(240, 240, 240, 1),
    white: Color.rgba(255, 255, 255, 1),
    grey4: Color.rgba(217, 217, 217, 1),
    middleBlue: Color.rgba(81, 102, 117, 1),
    lightBlue: Color.rgba(141, 176, 201, 1),
    goldMain: Color.rgba(198, 170, 118, 1),
    redError: Color.rgba(208, 2, 27, 1)
};

const legrandePortals20200301Typography = {
    heading3: new Typograph({ letterSpacing: 0, fontSize: 26, lineHeight: 39, color: Color.rgba(14, 36, 57, 1), font: new Font({ name: "OpenSans-Bold" }) }),
    heading2: new Typograph({ letterSpacing: 0, fontSize: 30, lineHeight: 35, color: Color.rgba(14, 36, 57, 1), font: new Font({ name: "OpenSans-Bold" }) }),
    xl: new Typograph({ letterSpacing: 0, fontSize: 40, lineHeight: 51, color: Color.rgba(14, 36, 57, 1), font: new Font({ name: "ABeeZee-Regular" }) }),
    l: new Typograph({ letterSpacing: 0, fontSize: 30, lineHeight: 35, color: Color.rgba(14, 36, 57, 1), font: new Font({ name: "OpenSans-Bold" }) })
};

export const legrandePortals20200301Tokens = {
    colors: legrandePortals20200301Colors,
    typography: legrandePortals20200301Typography
};
